// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU8zePOhSm5Uu3CVGwh6MS1FOCcG1e7NA',
    appId: '1:1078392536745:web:bb0fc136b42c944bc233b8',
    messagingSenderId: '1078392536745',
    projectId: 'flutterproject-3ccae',
    authDomain: 'flutterproject-3ccae.firebaseapp.com',
    storageBucket: 'flutterproject-3ccae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJwykS7R4ucGidgPrfFQQoX8yNcbpGdc8',
    appId: '1:1078392536745:android:4ee2d513854a290ec233b8',
    messagingSenderId: '1078392536745',
    projectId: 'flutterproject-3ccae',
    storageBucket: 'flutterproject-3ccae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8zA9sjrL0o7bFjMZ_25h-gQ8XxbpDUP4',
    appId: '1:1078392536745:ios:4817e14c9d9b4d77c233b8',
    messagingSenderId: '1078392536745',
    projectId: 'flutterproject-3ccae',
    storageBucket: 'flutterproject-3ccae.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8zA9sjrL0o7bFjMZ_25h-gQ8XxbpDUP4',
    appId: '1:1078392536745:ios:12425fd37ac0d6c0c233b8',
    messagingSenderId: '1078392536745',
    projectId: 'flutterproject-3ccae',
    storageBucket: 'flutterproject-3ccae.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
